version: '3'

services:
  app:
    build: app
    command: ["python3", "main.py"]
    volumes:
      - ./app:/app
    environment:
      - FLASK_APP=main.py
      - FLASK_HOST=0.0.0.0
      - OPENWEATHERMAP_API_KEY=446e855d59a06479bad6d4036c1fd77b    
    ports:
      - "5000:5000"

  ui:
    build: ui
    command: ["npm", "start"]
    volumes:
      - ./ui:/ui
    environment:
      - NODE_ENV=production
    ports:
      - '3000:3000'
    depends_on:
      - app
